# Nginx - Reverse proxy avec deux virtual hosts
# Écoute sur le port 80 et redirige vers le bon conteneur PHP selon le nom de domaine

# Version PRODUCTION : base de données MySQL
server {
    listen 80;
    server_name app.gestion-produits.local;

    location / {
        # "php-prod" = nom du service dans docker-compose
        proxy_pass         http://php-prod:80;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_read_timeout 90;
    }
}

# Version DEV : base de données PostgreSQL
server {
    listen 80;
    server_name dev.gestion-produits.local;

    location / {
        # "php-dev" = nom du service dans docker-compose
        proxy_pass         http://php-dev:80;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_read_timeout 90;
    }
}
