# Nginx - Reverse proxy avec HTTPS et deux virtual hosts
# HTTP → HTTPS redirect
server {
    listen 80;
    server_name app.gestion-produits.local dev.gestion-produits.local;
    return 301 https://$host$request_uri;
}

# Version PRODUCTION : base de données MySQL
server {
    listen 443 ssl;
    server_name app.gestion-produits.local;

    ssl_certificate     /etc/nginx/certs/gestion-produits.crt;
    ssl_certificate_key /etc/nginx/certs/gestion-produits.key;

    location / {
        proxy_pass         http://php-prod:80;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_read_timeout 90;
    }
}

# Version DEV : base de données PostgreSQL
server {
    listen 443 ssl;
    server_name dev.gestion-produits.local;

    ssl_certificate     /etc/nginx/certs/gestion-produits.crt;
    ssl_certificate_key /etc/nginx/certs/gestion-produits.key;

    location / {
        proxy_pass         http://php-dev:80;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_read_timeout 90;
    }
}
