# Secret pour PostgreSQL (environnement dev)
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: dev
type: Opaque
data:
  # "rootpassword" en base64
  db-password: cm9vdHBhc3N3b3Jk
  # "postgres" en base64
  db-user: cG9zdGdyZXM=
  # "gestion_produits" en base64
  db-name: Z2VzdGlvbl9wcm9kdWl0cw==
